export const FIELDS = [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Mechanical Engineering',
    'Aeronautical Engineering',
    'Instrumentation and Control Engineering',
    'IT Engineering',
    'Pharmacy',
    'BSc. Maths',
    'BSc. Physics',
    'BSc. Chemistry',
    'Obstetrics and Gynaecology',
    'Orthopaedics',
    'General Medicine',
    'Paediatrics',
    'Radiology',
    'General surgery',
    'Opthalmology',
    'Forensic Medicine',
    'ENT',
    'Anatomy',
    'MSc. Maths',
    'MSc. Physics',
    'MSc. Chemistry',
]